# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

payment_controllers:
    resource:
        path: ../src/Payment/Presentation/Controller/
        namespace: App\Payment\Presentation\Controller
    type: attribute
